# Generated by Django 4.0.6 on 2022-07-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='Country',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
