# Generated by Django 4.0.6 on 2022-07-11 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserDetail', '0002_alter_userdetail_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='UserId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
