# Generated by Django 4.0.6 on 2022-07-10 07:44

import Bill.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('BillId', models.IntegerField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField(default=0)),
                ('BillGenDate', models.DateField(auto_now_add=True)),
                ('BillDueDate', models.DateField(default=Bill.models.get_duedate)),
                ('Unit', models.IntegerField(default=0)),
                ('Paid', models.BooleanField(default=False)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
