# Generated by Django 4.0.6 on 2022-07-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='BillId',
        ),
        migrations.AddField(
            model_name='bill',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
