# Generated by Django 4.0.6 on 2022-07-10 08:00

import Bill.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0002_remove_bill_billid_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='BillDueDate',
            field=models.DateField(default=Bill.models.get_duedate, editable=False),
        ),
    ]
