# Generated by Django 4.0.6 on 2022-07-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0003_alter_bill_billduedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='BillDueDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='BillGenDate',
            field=models.DateField(),
        ),
    ]
