# Generated by Django 4.0.6 on 2022-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0004_alter_bill_billduedate_alter_bill_billgendate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='BillDueDate',
            field=models.DateField(null=True),
        ),
    ]
