# Generated by Django 4.0.6 on 2022-07-15 09:34

import Bill.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0005_alter_bill_billduedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='BillDueDate',
            field=models.DateField(default=Bill.models.get_duedate, editable=False),
        ),
    ]
