# Generated by Django 4.0.6 on 2022-07-15 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bill', '0003_alter_bill_billduedate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillReport',
            fields=[
                ('ReportId', models.IntegerField(primary_key=True, serialize=False)),
                ('Remarks', models.CharField(max_length=2000)),
                ('Status', models.BooleanField(default=False)),
                ('BillId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bill.bill')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
